### ISSUE TITLE
Epic: Recipe Management

### ISSUE THREAD

**Issue by behemot-biz** [behemot-biz/tt-drf#18]
### Tasks under this Epic:
- [x] #2 Implement Create Recipe API endpoint
- [ ] #5 Implement Edit Recipe API endpoint
- [ ] #6 Implement Delete Recipe API endpoint
- [ ]  #4 Implement View Recipe Details API endpoint
- [ ]  #3 Implement List Recipes API endpoint
- [ ] #28 Implement Create RecipeIngredient API endpoint
- [ ] #29 Implement Edit RecipeIngredient API endpoint
- [ ] #30 Implement List RecipeIngredient API endpoint
- [ ] #31 Implement Delete RecipeIngredient API endpoint

**Goal**: Enable users to manage their recipes.
