### ISSUE TITLE
Epic: Profile Management

### ISSUE THREAD

**Issue by behemot-biz** [behemot-biz/tt-drf#21]
### Tasks under this Epic:

- [ ] #7 Implement View Profile API endpoint
- [ ] #8 Implement View Profile Details API endpoint
- [ ] #9 Implement Update Profile Details API endpoint

**Goal**: Enable users to view and update profiles
